#!/usr/bin/env bash

#if [[ $(git diff --shortstat 2> /dev/null | tail -n1) != "" ]]; then
#    echo -e "\e[31m\e[1mGit is dirty. \e[0mPlease commit changes first."
#    exit 1
#fi

set -e

version=$(date +"%y%m%d")

git checkout -b release/${version} develop
npm run prod
git commit -a -m "Pre-release $version"
